### ISSUE TITLE
potential numbering issue: 5drx 

### ISSUE THREAD

**Issue by biochunan** [AndrewCRMartin/absplit#15]
AbM numbered **5drx_0** and **5drx_1P** CDR-H3 included a piece of framework region.

**Comment by AndrewCRMartin** [comment]
This is a problem in `abnum` which is over-sensitive to needing `WG` immediately after CDR-H3 - this sequence has WA.

This is now logged as an issue in `abnum`. It would, however, make sense to look for errors like this in `absplit`.

**Comment by AndrewCRMartin** [comment]
Similarly - CDR-H3 in 7jz4_0 and 7jz4_1H is insertion of a LAIR1 domain (~109 residue long)

Current assignment is a slice of LAIR1

We need to be able to reject things that don't have residues H103... as ".bad"
