### ISSUE TITLE
pdb6ca6_0P and pdb6ca6_1P: no antigen present, chain-splitting issue 

### ISSUE THREAD

**Issue by biochunan** [AndrewCRMartin/absplit#18]
6ca6 contains two antibodies and no antigen is present in this PDB file except for two small molecules (ether and glycerol)
- Fab 1: chian A and B
- Fab 2: chain H and L 

In preliminary version of the new release (`/serv/data/abdb_newdata`): `pdb6ca6_0P.mar` and `pdb6ca6_1P.mar` each contains a single heavy chain.

**Comment by AndrewCRMartin** [comment]
Fixed
