### ISSUE TITLE
pdb6muf_0PH.mar: missing antibody

### ISSUE THREAD

**Issue by biochunan** [AndrewCRMartin/absplit#19]
`pdb6muf_0PH` only contains the antigen, antibody with original chain id `D` and `E` should be included.

**Comment by AndrewCRMartin** [comment]
Similarly pdb6wix_0PH

**Comment by AndrewCRMartin** [comment]
Closing as this is another case where _0 is not numbered so now has a .bad file
_1 is fine

Will only be improved more by updates to abnum
